governance_demo:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: not_a_real_account
      user: not_a_real_user
      password: not_a_real_password
      role: not_a_real_role
      database: not_a_real_database
      warehouse: not_a_real_warehouse
      schema: not_a_real_schema
      threads: 1